######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 7 21:10:30 2009
######################################################################

TEMPLATE = app
QT += widgets
TARGET = inputmask
DEPENDPATH += .
INCLUDEPATH += .

HEADERS += masktestform.h
SOURCES += maskmain.cpp masktestform.cpp
