######################################################################
# Automatically generated by qmake (2.00a) Fri Aug 5 15:48:00 2005
######################################################################

TEMPLATE = app
QT += widgets
DEPENDPATH += .
INCLUDEPATH += .

HEADERS += rinputform.h
SOURCES += regexvalidate.cpp rinputform.cpp
